"""
ai_implementation_guide.py - AI调用频率控制实施指南
提供具体的代码示例和实施步骤，帮助用户快速集成API频率控制
"""

def generate_implementation_guide():
    """生成AI调用频率控制实施指南"""
    
    report = []
    report.append("=== AI调用频率控制实施指南 ===")
    report.append(f"创建时间: 2026-06-18 15:35:00")
    report.append("")
    
    # 快速开始
    report.append("### 🚀 快速开始")
    report.append("")
    report.append("#### 1. 导入API频率控制模块")
    report.append("```python")
    report.append("from api_frequency_control import (")
    report.append("    APILimiter,")
    report.append("    api_limiter,")
    report.append("    batch_processor,")
    report.append("    concurrent_processor,")
    report.append("    APIMonitor,")
    report.append("    safe_api_call")
    report.append(")")
    report.append("```")
    report.append("")
    
    report.append("#### 2. 基础使用示例")
    report.append("```python")
    report.append("# 创建API限流器")
    report.append("limiter = APILimiter(max_calls_per_minute=30, max_calls_per_hour=200)")
    report.append("")
    report.append("# 使用装饰器进行API限流")
    report.append("@api_limiter(max_calls_per_minute=30, max_calls_per_hour=200)")
    report.append("def ai_stock_analysis(stock_data):")
    report.append("    # AI分析逻辑")
    report.append("    return f'分析结果: {stock_data}'")
    report.append("```")
    report.append("")
    
    # 具体场景实施
    report.append("### 📊 具体场景实施")
    report.append("")
    
    # 场景1: 股票批量分析
    report.append("#### 场景1: 股票批量分析")
    report.append("```python")
    report.append("def batch_stock_analysis(stock_list):")
    report.append("    \"\"\"批量股票分析，避免API调用超限\"\"\"")
    report.append("    ")
    report.append("    def analyze_stock(stock):")
    report.append("        # 模拟AI分析")
    report.append("        time.sleep(0.5)")
    report.append("        return f'{stock}: 分析完成'")
    report.append("    ")
    report.append("    # 使用批量处理器")
    report.append("    return batch_processor(")
    report.append("        stock_list,")
    report.append("        analyze_stock,")
    report.append("        batch_size=10,  # 每批次10只股票")
    report.append("        delay=1.0,      # 批次间延迟1秒")
    report.append("        max_workers=3   # 最大并发数")
    report.append("    )")
    report.append("```")
    report.append("")
    
    # 场景2: 并发数据处理
    report.append("#### 场景2: 并发数据处理")
    report.append("```python")
    report.append("def concurrent_data_processing(tasks):")
    report.append("    \"\"\"并发数据处理，控制并发数量\"\"\"")
    report.append("    ")
    report.append("    def process_task(task):")
    report.append("        # 模拟数据处理")
    report.append("        time.sleep(0.3)")
    report.append("        return f'任务 {task}: 完成'")
    report.append("    ")
    report.append("    # 使用并发处理器")
    report.append("    return concurrent_processor(")
    report.append("        tasks,")
    report.append("        process_task,")
    report.append("        max_workers=3,  # 限制并发数")
    report.append("        delay=0.5       # 并发任务间延迟")
    report.append("    )")
    report.append("```")
    report.append("")
    
    # 场景3: AI报告生成
    report.append("#### 场景3: AI报告生成")
    report.append("```python")
    report.append("def generate_ai_report(data):")
    report.append("    \"\"\"AI报告生成，带有重试机制\"\"\"")
    report.append("    ")
    report.append("    def ai_generate_report(report_data):")
    report.append("        # 模拟AI生成报告")
    report.append("        if random.random() < 0.1:  # 10%概率失败")
    report.append("            raise Exception('AI生成失败')")
    report.append("        return f'报告: {report_data}'")
    report.append("    ")
    report.append("    # 使用安全的API调用")
    report.append("    return safe_api_call(")
    report.append("        lambda: ai_generate_report(data),")
    report.append("        api_name='AI报告生成',")
    report.append("        max_retries=3,")
    report.append("        retry_delay=2.0")
    report.append("    )")
    report.append("```")
    report.append("")
    
    # 场景4: 实时监控
    report.append("#### 场景4: 实时监控")
    report.append("```python")
    report.append("class AIBatchMonitor:")
    report.append("    \"\"\"AI批量监控器\"\"\"")
    report.append("    ")
    report.append("    def __init__(self):")
    report.append("        self.monitor = APIMonitor()")
    report.append("    ")
    report.append("    def monitor_batch_processing(self, batch_name, items):")
    report.append("        \"\"\"监控批量处理\"\"\"")
    report.append("        start_time = time.time()")
    report.append("        ")
    report.append("        for item in items:")
    report.append("            try:")
    report.append("                # 模拟处理")
    report.append("                result = f'处理 {item}'")
    report.append("                duration = time.time() - start_time")
    report.append("                ")
    report.append("                # 记录成功调用")
    report.append("                self.monitor.log_call(")
    report.append("                    batch_name,")
    report.append("                    success=True,")
    report.append("                    duration=duration")
    report.append("                )")
    report.append("                ")
    report.append("            except Exception as e:")
    report.append("                # 记录失败调用")
    report.append("                self.monitor.log_call(")
    report.append("                    batch_name,")
    report.append("                    success=False,")
    report.append("                    duration=time.time() - start_time,")
    report.append("                    error_msg=str(e)")
    report.append("                )")
    report.append("        ")
    report.append("        return self.monitor.get_stats()")
    report.append("```")
    report.append("")
    
    # 高级配置
    report.append("### ⚙️ 高级配置")
    report.append("")
    
    report.append("#### 1. 自定义限流策略")
    report.append("```python")
    report.append("class CustomAPILimiter(APILimiter):")
    report.append("    \"\"\"自定义API限流器\"\"\"")
    report.append("    ")
    report.append("    def __init__(self, config):")
    report.append("        super().__init__(")
    report.append("            max_calls_per_minute=config.get('minute_limit', 30),")
    report.append("            max_calls_per_hour=config.get('hour_limit', 200),")
    report.append("            max_calls_per_day=config.get('day_limit', 1000)")
    report.append("        )")
    report.append("        self.config = config")
    report.append("    ")
    report.append("    def check_limit_with_priority(self, priority='normal'):")
    report.append("        \"\"\"带优先级的限流检查\"\"\"")
    report.append("        if priority == 'high':")
    report.append("            # 高优先级任务放宽限制")
    report.append("            return self.minute_calls < self.max_calls_per_minute * 1.5")
    report.append("        elif priority == 'low':")
    report.append("            # 低优先级任务严格限制")
    report.append("            return self.minute_calls < self.max_calls_per_minute * 0.5")
    report.append("        else:")
    report.append("            return self.check_limit()")
    report.append("```")
    report.append("")
    
    report.append("#### 2. 智能重试策略")
    report.append("```python")
    report.append("def smart_retry_api_call(api_func, max_retries=3, backoff_factor=2.0):")
    report.append("    \"\"\"智能重试API调用\"\"\"")
    report.append("    ")
    report.append("    for attempt in range(max_retries):")
    report.append("        try:")
    report.append("            result = api_func()")
    report.append("            return result")
    report.append("        except Exception as e:")
    report.append("            if attempt == max_retries - 1:")
    report.append("                raise")
    report.append("            ")
    report.append("            # 指数退避")
    report.append("            wait_time = backoff_factor ** (attempt + 1)")
    report.append("            logger.warning(f'API调用失败，{wait_time}秒后重试: {e}')")
    report.append("            time.sleep(wait_time)")
    report.append("```")
    report.append("")
    
    # 性能优化
    report.append("### 🚀 性能优化")
    report.append("")
    
    report.append("#### 1. 缓存机制")
    report.append("```python")
    report.append("from functools import lru_cache")
    report.append("")
    report.append("@lru_cache(maxsize=1000)")
    report.append("def cached_ai_analysis(stock_data):")
    report.append("    \"\"\"带缓存的AI分析\"\"\"")
    report.append("    return ai_analysis(stock_data)")
    report.append("```")
    report.append("")
    
    report.append("#### 2. 异步处理")
    report.append("```python")
    report.append("import asyncio")
    report.append("")
    report.append("async def async_batch_processing(items):")
    report.append("    \"\"\"异步批量处理\"\"\"")
    report.append("    ")
    report.append("    async def process_item(item):")
    report.append("        await asyncio.sleep(0.5)")
    report.append("        return f'处理 {item}'")
    report.append("    ")
    report.append("    tasks = [process_item(item) for item in items]")
    report.append("    return await asyncio.gather(*tasks)")
    report.append("```")
    report.append("")
    
    # 监控和报警
    report.append("### 📊 监控和报警")
    report.append("")
    
    report.append("#### 1. 实时监控")
    report.append("```python")
    report.append("class APIMonitorSystem:")
    report.append("    \"\"\"API监控系统\"\"\"")
    report.append("    ")
    report.append("    def __init__(self):")
    report.append("        self.monitors = {}")
    report.append("    ")
    report.append("    def add_monitor(self, name):")
    report.append("        self.monitors[name] = APIMonitor()")
    report.append("        return self.monitors[name]")
    report.append("    ")
    report.append("    def get_system_stats(self):")
    report.append("        \"\"\"获取系统整体统计\"\"\"")
    report.append("        stats = {}")
    report.append("        for name, monitor in self.monitors.items():")
    report.append("            stats[name] = monitor.get_stats()")
    report.append("        return stats")
    report.append("    ")
    report.append("    def check_system_health(self):")
    report.append("        \"\"\"检查系统健康状态\"\"\"")
    report.append("        for name, monitor in self.monitors.items():")
    report.append("            stats = monitor.get_stats()")
    report.append("            if stats['success_rate'] < 0.9:")
    report.append("                logger.warning(f'{name} API成功率过低: {stats[\"success_rate\"]:.2%}')")
    report.append("            if stats['recent_errors'] > 10:")
    report.append("                logger.warning(f'{name} API错误过多: {stats[\"recent_errors\"]}')")
    report.append("```")
    report.append("")
    
    # 部署建议
    report.append("### 🚀 部署建议")
    report.append("")
    
    report.append("#### 1. 立即部署")
    report.append("```python")
    report.append("    report.append(\"# 1. 在现有系统中集成API频率控制\")")
    report.append("from api_frequency_control import APILimiter")
    report.append("")
    report.append("# 2. 为所有AI分析函数添加限流装饰器")
    report.append("@api_limiter(max_calls_per_minute=30, max_calls_per_hour=200)")
    report.append("def existing_ai_function(data):")
    report.append("    # 现有AI分析逻辑")
    report.append("    pass")
    report.append("```")
    report.append("")
    
    report.append("#### 2. 配置优化")
    report.append("```python")
    report.append("# 根据系统负载调整配置")
    report.append("config = {")
    report.append("    'minute_limit': 20,    # 每分钟限制")
    report.append("    'hour_limit': 100,     # 每小时限制")
    report.append("    'day_limit': 500,      # 每天限制")
    report.append("    'batch_size': 5,       # 批次大小")
    report.append("    'batch_delay': 2.0,    # 批次延迟")
    report.append("    'max_workers': 2      # 最大并发数")
    report.append("}")
    report.append("")
    report.append("# 创建自定义限流器")
    report.append("custom_limiter = APILimiter(**config)")
    report.append("```")
    report.append("")
    
    # 测试和验证
    report.append("### 🧪 测试和验证")
    report.append("")
    
    report.append("#### 1. 单元测试")
    report.append("```python")
    report.append("import unittest")
    report.append("from api_frequency_control import APILimiter")
    report.append("")
    report.append("class TestAPILimiter(unittest.TestCase):")
    report.append("    def test_limit_control(self):")
    report.append("        limiter = APILimiter(max_calls_per_minute=5)")
    report.append("        ")
    report.append("        # 测试正常调用")
    report.append("        for i in range(5):")
    report.append("            self.assertTrue(limiter.check_limit())")
    report.append("            limiter.increment()")
    report.append("        ")
    report.append("        # 测试限制触发")
    report.append("        self.assertFalse(limiter.check_limit())")
    report.append("```")
    report.append("")
    
    report.append("#### 2. 集成测试")
    report.append("```python")
    report.append("def test_batch_processing():")
    report.append("    \"\"\"测试批量处理功能\"\"\"")
    report.append("    items = list(range(20))")
    report.append("    ")
    report.append("    def mock_process(item):")
    report.append("        time.sleep(0.1)")
    report.append("        return item * 2")
    report.append("    ")
    report.append("    results = batch_processor(")
    report.append("        items, mock_process, batch_size=5, delay=0.5")
    report.append("    )")
    report.append("    ")
    report.append("    assert len(results) == 20")
    report.append("    assert all(r == i * 2 for i, r in enumerate(results))")
    report.append("```")
    report.append("")
    
    # 故障排除
    report.append("### 🔧 故障排除")
    report.append("")
    
    report.append("#### 1. 常见问题")
    report.append("```python")
    report.append("    report.append(\"# 问题1: API调用仍然超限\")")
    report.append("解决方案:")
    report.append("1. 检查配置参数是否正确")
    report.append("2. 增加批次间延迟时间")
    report.append("3. 减少最大并发数")
    report.append("4. 检查是否有其他线程也在调用API")
    report.append("")
    report.append("# 问题2: 处理速度过慢")
    report.append("解决方案:")
    report.append("1. 适当增加批次大小")
    report.append("2. 减少批次间延迟")
    report.append("3. 增加并发线程数")
    report.append("4. 使用缓存机制")
    report.append("")
    report.append("# 问题3: 内存使用过高")
    report.append("解决方案:")
    report.append("1. 减少批次大小")
    report.append("2. 使用生成器处理大数据集")
    report.append("3. 定期清理缓存")
    report.append("```")
    report.append("")
    
    # 总结
    report.append("### 🎯 总结")
    report.append("")
    report.append("通过以上实施指南，您可以：")
    report.append("")
    report.append("1. **快速集成**: 使用装饰器和批量处理器快速集成API频率控制")
    report.append("2. **智能限流**: 根据系统需求调整限流策略")
    report.append("3. **性能优化**: 使用缓存和异步处理提高性能")
    report.append("4. **监控报警**: 实时监控系统状态并及时发现问题")
    report.append("5. **故障排除**: 快速定位和解决常见问题")
    report.append("")
    report.append("建议按照以下顺序实施：")
    report.append("")
    report.append("1. **第一阶段**: 集成基础限流功能")
    report.append("2. **第二阶段**: 优化批量处理和并发控制")
    report.append("3. **第三阶段**: 添加监控和报警")
    report.append("4. **第四阶段**: 性能优化和高级配置")
    report.append("")
    report.append("通过这些措施，可以有效避免API调用频率超限问题，确保系统稳定运行。")
    
    return "\n".join(report)


if __name__ == "__main__":
    guide = generate_implementation_guide()
    print(guide)
    
    # 保存指南到文件
    with open('ai_implementation_guide.txt', 'w', encoding='utf-8') as f:
        f.write(guide)
    
    print("\n=== 实施指南完成，报告已保存到 ai_implementation_guide.txt ===")